# Generated by Django 6.0.1 on 2026-01-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date',
        ),
    ]
