# Generated by Django 6.0.1 on 2026-02-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_images/7090544.jpg', upload_to='blog_images/'),
        ),
    ]
