# Generated by Django 6.0.1 on 2026-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/7090544.jpg', upload_to='images/'),
        ),
    ]
